### ISSUE TITLE
[FEATURE] dataclasses-json maintenance

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/adapta#239]
**Is your feature request related to a problem? Please describe.**
We are heavily dependent on this library, but it is no actively maintained. We can do one of three things:
- Offer the author help with contributions to keep the lib healthy
- Fork the lib/rewrite ourselves, maintaining the original API
- Find an alternative and migrate

**Describe the solution you'd like**
I'd say 1 or 2 are preferable options.

**Comment by matt035343** [comment]
@george-zubrienko I think we can close this one as we are now maintainers of dataclasses-json
