### ISSUE TITLE
[FEATURE] Unlock Python 3.11

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/adapta#255]
**Is your feature request related to a problem? Please describe.**
We should change Python version constraints to `>=3.9,<3.12` and add tests for 3.11.

**Comment by george-zubrienko** [comment]
fyi @JanusAsmussen @henrikfoss @matt035343

**Comment by george-zubrienko** [comment]
@JanusAsmussen @matt035343 should I also unlock pandas 2.0 or we are soon going polars anyway so meh?

**Comment by matt035343** [comment]
@george-zubrienko Even though we _may_ use polars at some point in the future, maybe not all applications will migrate immediately or migrate at all. Since Pandas 2.0 seems quite backwards compatible, I think it makes sense to allow people to upgrade pandas to 2.0
