### ISSUE TITLE
[FEATURE] Generalize the `load` method

### ISSUE THREAD

**Issue by matt035343** [SneaksAndData/adapta#327]
It would be nice if we could generalize the `load` method such that it accepts a socket and infers what driver API to use to load the data.

This could reduce the code duplication in our repos that load data. Especially in [SneaksAndData/omni-channel-crystal-solver](https://github.com/SneaksAndData/omni-channel-crystal-solver) and  [SneaksAndData/return-optimizer-crystal-solver](https://github.com/SneaksAndData/return-optimizer-crystal-solver).

The generalized version might not be a function, but could be OOP-based with a factory class to create a data loader instance.

**Comment by george-zubrienko** [comment]
After a very productive offline discussion with @matt035343 we'll implement the following:

1. All storages will be generalized into `StorageConnection` class which accepts a connection string in a format to be developed, similar to data paths in `DataSocket`
2. We'll add the following capability to that class:

```
  con = StorageConnection.from_connection_string('....')
  socket = DataSocket(...) # implemented already
  filters = (FilterField("col_a") == 1) & (FilterField("col_b") == "abc")
  
  my_data = con.load(socket, filters) # pd.DataFrame or ps.DataFrame
```

This will allow to use Astra, Azure, S3, SQL and any other storage data source interchangeably without adding boilerplate and reduce the number of environment variables we map to algorithm runner containers + unify all storage loading interfaces.

**Comment by george-zubrienko** [comment]
Implements https://github.com/SneaksAndData/adapta/issues/291
