### ISSUE TITLE
[QUESTION] Throw better error when forgetting to install extras

### ISSUE THREAD

**Issue by MetteGudik** [SneaksAndData/adapta#369]
**Describe the bug**
Forgot to install extra packages and got the error:
![image](https://github.com/SneaksAndData/adapta/assets/132268346/c2334f1c-a916-495f-8912-ed43efc3c6a3)
Going into the problem I learned that 
![image](https://github.com/SneaksAndData/adapta/assets/132268346/c032240d-d65d-4a74-9572-a8450546fbda)
was the actual problem.

**To Reproduce**
Try accessing the AzureClient in a poetry environment without the extra package "adlfs"

**Expected behavior**
I would like the error message to show the real problem and not the "upper layer" of the problem. Meaning I want to see the
 ![image](https://github.com/SneaksAndData/adapta/assets/132268346/c032240d-d65d-4a74-9572-a8450546fbda)
when forgetting to install extras. 

**Additional context**
I suspect that this will be a problem with all  extras packages, and I would like this to be fixed for them all. Could probably be fixed by throwing better exception:
![image](https://github.com/SneaksAndData/adapta/assets/132268346/82d3d8e5-7577-4fbd-8e26-37c16aaa09f8)

**Comment by george-zubrienko** [comment]
@MetteGudik are you sure if you read the full stack trace you will not see the root error?

**Comment by george-zubrienko** [comment]
Closing based on offline discussion as not planned
