### ISSUE TITLE
[FEATURE] Docstring formatting util

### ISSUE THREAD

**Issue by matt035343** [SneaksAndData/adapta#41]
I have just written following code:
```
def format_docstring(*params):
    """
    Replaced bracketed parameters in docstring with the passed formatting parameters.
    Example::

    @format_docstring('SkuId')
    def func():
        \"\"\"
        I only affect following column: {0}
        \"\"\"
        pass

    :param params: The parameters to format in the docstring.
    """
    def dec(obj):
        obj.__doc__ = obj.__doc__.format(*params)
        return obj
    return dec

```

I believe this can be useful for other people. @george-zubrienko do you believe util like this belongs in this package?
(or do you have a better way of doing the same?)

**Comment by george-zubrienko** [comment]
@matt035343 chatgpt solves this? :)

**Comment by matt035343** [comment]
@george-zubrienko  I think we can close this as not planned. I no longer need and and frankly I do not remember why I needed this in the first place.
