### ISSUE TITLE
[SMELL] Change DD logging env var names

### ISSUE THREAD

**Issue by matt035343** [SneaksAndData/adapta#96]
https://github.com/SneaksAndData/proteus/blob/03cf92e86fd94925e15270fb31b1cce347d464dd/proteus/logs/handlers/datadog_api_handler.py#L38-L41

Should be consistent with

https://github.com/SneaksAndData/proteus/blob/03cf92e86fd94925e15270fb31b1cce347d464dd/proteus/metrics/providers/datadog_provider.py#L33-L37

**Comment by george-zubrienko** [comment]
Closing as this is dupicate of #49
